#Specify base image
FROM node:18-alpine

#Set a working directory
WORKDIR '/app'

#Copy the package.json file to the working directory
COPY package.json .
#Install dependencies
RUN npm install

#Copy the rest of the files to the working directory
COPY . .

#Set default command
CMD ["npm", "run", "start"]