name: Deploy 
on: 
  push: 
    branches: 
      - master

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: run tests 
        run: npm run test 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build
            README.md
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: list files
        run: ls
      - name: deploy
        run: echo "Deploying to production c:"


