name: First Workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate
        run: | 
          echo "Initiating ${{ github.workflow }}"
          echo "${{ github.workflow}} initiated"
      - name: Close
        run: | 
          echo "Closing ${{ github.workflow }}"
          echo "${{ github.workflow }} closed"
      - name: End
        run: echo "End ${{ github.workflow }}"
  
