name: on-issue-opened
on:
    issues:
        types: [opened]

jobs:
    issue-opened:
        runs-on: ubuntu-latest
        steps:
            - name: Display event details
              run: | 
                echo "Issue opened by ${{ github.actor}}"
                echo "Issue titled: ${{ github.event.issue.title}}"
                ASSIGNEE="${{github.event.issue.assignee.login}}"
                if [ ! -z "$ASSIGNEE" ]; then
                    echo "Issue assigned to $ASSIGNEE"
                else
                    echo "Issue not assigned"
                fi