name: Matrix Demo with reusable workflow
on:
    push:
        branches:
            - master
jobs:
    welcome:
        uses: ./.github/workflows/welcome-reusable.yml
        with:
            name_of_job: 'Matrix Demo Job'
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [14, 18]
        outputs:
            current-node-version: ${{ steps.node-version.outputs.current-node-version }}
        runs-on: ubuntu-latest
        steps:
          - name: Get Code
            uses: actions/checkout@v3
          - name: Install Node.js
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version}}
          - name: Install Dependencies
            run: npm install
          - name: Build Project
            run: npm run build
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: build-node-${{ matrix.node-version }}
              path: build
          - name: Output node version
            id: node-version
            run: echo "current-node-version=${{ matrix.node-version }}" >> $GITHUB_OUTPUT
              
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: deploy node version
            run: echo "Deploying with node version ${{ needs.build.outputs.current-node-version }}"