name: test-on-push 
on: push
jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: run tests 
        run: npm run test


